name: ❓ General Question
description: Submit a general question.
assignees:
  - maxileith
labels:
  - general question

body:
  - type: markdown
    attributes:
      value: |
        ### Hello there!

        Before we start. Make sure that the question you are having is not a [support request](https://github.com/maxileith/homebridge-appletv-enhanced/issues/new?template=2-support_request.yml).

  - type: textarea
    id: analysis
    attributes:
      label: Issue
      description: Please provide a concise description of the issue.
    validations:
      required: true
