name: 🚀 Feature Request
description: Suggest an improvement or a new feature for this project.
assignees:
  - maxileith
labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        ### Hello there!

        Thanks for taking the time to contribute to Apple TV Enhanced! :heart:

        ### Preconditions

        Before we start, be sure you are aware of the following points:

        - Check whether or not the feature you are having on your mind has been suggested in the past: [closed feature requests](https://github.com/maxileith/homebridge-appletv-enhanced/issues?q=is%3Aissue+is%3Aclosed+label%3Aenhancement)
          - If not, please explain why this improvement makes sense nowadays.

  - type: textarea
    id: problem
    attributes:
      label: Current Situation
      description: Please provide an overview of the current situation and illustrate potential problems or shortcomings.
      placeholder: A clear and concise description of the problem or situation that should be addressed.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Change
      description: Please provide a clear and concise description of the solution or change you propose and how it should work.
      placeholder: A clear and concise description of the solution or change you propose and how it should work.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Please provide any additional context that might be relevant for your request.
      placeholder: Any additional context that might be relevant for your request.
