name: 🤷🏼‍♂️ Other
description: Submit an issue that is not covered by any other template (bug report, support request, feature request, general question).
assignees:
  - maxileith

body:
  - type: markdown
    attributes:
      value: |
        ### Hi!

        Thanks for taking the time to submit an issue. This issue template should only be used if non of the following issue templates is a good fit for the issue that you want to submit:

        - [bug report](https://github.com/maxileith/homebridge-appletv-enhanced/issues/new?template=4-bug_report.yml)
        - [support request](https://github.com/maxileith/homebridge-appletv-enhanced/issues/new?template=2-support_request.yml)
        - [feature request](https://github.com/maxileith/homebridge-appletv-enhanced/issues/new?template=3-feature_request.yml)
        - [general question](https://github.com/maxileith/homebridge-appletv-enhanced/issues/new?template=1-general_question.yml)

  - type: checkboxes
    attributes:
      label: Preconditions
      options:
        - label: The issue is not covered by any of the other issue templates
          required: true

  - type: textarea
    id: analysis
    attributes:
      label: Issue
      description: Please provide a concise description of the issue.
    validations:
      required: true
