blank_issues_enabled: false
contact_links:
  - name: 👥 GitHub Community Support
    url: https://github.com/maxileith/homebridge-appletv-enhanced/discussions
    about: If you do not expect an answer of the maintainer but rather want a discussion with the community, please open a GitHub discussions.
