blank_issues_enabled: false
contact_links:
  - name: 🎤 Discord
    url: https://discord.com/channels/432663330281226270/1289375141872275476
    about: AppleTV Enhanced channel on the official homebridge discord server.
