name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ubuntu-latest Node 20 Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version-file: .nvmrc

      - name: Build
        run: npm run build
