name: Issue completeness check

on:
  issues:
    types:
      - opened
      - edited
      - reopened
  issue_comment:
    types:
      - created

jobs:
  is_issue_complete:
    name: "Check if issue #${{ github.event.issue.number }} is complete"
    runs-on: ubuntu-latest
    permissions:
      issues: write

    if: (github.event_name == 'issues' && (contains(github.event.issue.labels.*.name, 'bug') || contains(github.event.issue.labels.*.name, 'support request'))) || (github.event_name == 'issue_comment' && github.event.comment.body == '/check')

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            package.json
            src/PythonChecker.ts
            .github/issue_completeness_check

      - name: Use Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Print Python version
        shell: bash
        run: python3 --version

      - name: Upgrade Pip
        shell: bash
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        shell: bash
        run: python3 -m pip install -r .github/issue_completeness_check/requirements.txt

      - name: Run check
        shell: bash
        run: python3 .github/issue_completeness_check/check.py ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
